// ─── DIGITAL TWIN WORKSPACE TYPES ──────────────────────────────────────────

export type DigitalTwinDomain =
  | "biological"
  | "physical"
  | "environmental"
  | "engineered"
  | "musical"
  | "conceptual"
  | "hybrid";

export interface BoundaryChannel {
  id: string;
  name: string;
  type: string; // e.g. "air", "water", "data", "heat", "acoustic_energy", "particle"
  rate?: string;
  medium?: string;
}

export interface BoundaryRule {
  id: string;
  inputType: string;
  condition: string;
  action: "permit" | "reject" | "attenuate" | "store" | "convert" | "redirect";
  parameters?: Record<string, number | string | boolean>;
}

export interface TwinBoundary {
  description: string;
  includedEntities: string[];
  excludedEntities: string[];
  inputs: BoundaryChannel[];
  outputs: BoundaryChannel[];
  permeabilityRules?: BoundaryRule[];
}

export interface SourceAsset {
  id: string;
  name: string;
  type: string;
  size?: string;
  url?: string;
  timestamp: string;
}

export interface TwinEntity {
  id: string;
  name: string;
  type: string;
  state: Record<string, unknown>;
  description?: string;
  status?: "active" | "warning" | "error" | "offline";
}

export interface TwinRelationship {
  id: string;
  sourceId: string;
  targetId: string;
  relationshipType: string;
  medium?: string;
  strength?: number; // 0 to 1
  latency?: number; // in ms
  direction?: "one_way" | "two_way" | "field";
}

export interface TwinState {
  id: string;
  name: string;
  metrics: Record<string, unknown>;
  timestamp: string;
  active?: boolean;
}

export type EvidenceClassification =
  | "surviving_physical"
  | "inscription_derived"
  | "reconstruction"
  | "hypothesis"
  | "counterfactual_simulation";

export interface Observation {
  id: string;
  fact: string;
  value: string;
  isFact: boolean; // true = Fact/Measured, false = Inference/Assumption
  timestamp: string;
  quality?: "measured" | "inferred" | "sensor";
  evidenceClass?: EvidenceClassification;
  sourceAssetId?: string;
}

export interface Interpretation {
  id: string;
  claim: string;
  evidenceIds: string[];
  confidence: number; // 0 to 100
  status: "observed" | "inferred" | "challenged" | "approved" | "rejected";
  createdAt: string;
  author?: string;
}

export interface SimulationPerturbation {
  targetGear?: string;
  nominalTeeth?: number;
  perturbedTeeth?: number;
  toothDelta?: number;
  moduleMm?: number;
  centerDistanceMm?: number;
  backlashMm?: number;
  pitchErrorMm?: number;
  frictionCoeff?: number;
  targetRelationship?: string;
  description?: string;
  assumptions?: string[];
  [key: string]: any;
}

export interface SimulationBaselineState {
  id?: string;
  name: string;
  description?: string;
  targetRatio?: string;
  nominalTeeth?: number;
  moduleMm?: number;
  centerDistanceMm?: number;
  status?: string;
  [key: string]: any;
}

export type ComputeRail = 
  | "NVIDIA_NIM" 
  | "RAPIDS_GPU" 
  | "OPEN_SOURCE_INFERENCE"
  | "LOCAL_DETERMINISTIC" 
  | "CUSTOM_PDE"
  | "FPT_AI_CLOUD"; // Preserved for historical provenance reading; runtime dispatch is REVOKED

export type RailTrustState = 
  | "APPROVED"
  | "EXPERIMENTAL"
  | "UNVERIFIED"
  | "SUSPENDED"
  | "REVOKED";

export type DeploymentMode = 
  | "HOSTED_EXTERNAL"
  | "SELF_HOSTED_REMOTE"
  | "LOCAL"
  | "OFFLINE_LOCAL";

export type CredentialState = 
  | "CONFIGURED"
  | "NOT_REQUIRED"
  | "MISSING"
  | "INVALID"
  | "REVOKED";

export type RailHealthState = 
  | "HEALTHY"
  | "DEGRADED"
  | "UNREACHABLE"
  | "REVOKED"
  | "UNKNOWN";

export interface InferenceRail {
  rail_id: string;
  provider: string;
  runtime: string; // e.g. "nvidia-nim", "vllm", "tgi", "local-deterministic", "cloud-gemini"
  deployment_mode: DeploymentMode;
  model_id: string;
  endpoint: string;
  capabilities: string[];
  trust_state: RailTrustState;
  credential_state: CredentialState;
  health_state: RailHealthState;
  execution_location: string;
  trustRationale?: string;
}

export type SimulationLifecycleStatus = 
  | "PROPOSED_SIMULATION"   // Proposed simulation specification awaiting dispatch (not executed)
  | "COMPUTE_GENERATED"     // Raw outputs generated by external compute rail, pending validation
  | "VALIDATED_EVIDENCE";   // Validated against empirical data / Operator promoted into accepted twin state

export interface ComputeReceipt {
  selectedRail: ComputeRail;
  endpointOrModel: string;
  inputManifest: Record<string, any>;
  codeVersion: string;
  hardwareMetadata: {
    device: string;
    accelerator?: string;
    memoryGb?: number;
    cores?: number;
    runtimeDriver?: string;
  };
  rawOutputArtifact: Record<string, any> | Array<any> | string;
  timestamp: string;
  runId: string;
  uncertaintyAndConvergence: {
    converged: boolean;
    iterations?: number;
    residualError?: number;
    confidenceBounds?: string;
    notes?: string;
  };
  inputOutputHash: string;
  fallbackOrDegradedMode: string;
}

export interface JemmaProvenanceValidation {
  validated: boolean;
  unitsChecked: boolean;
  completenessScore: number;
  evidenceClass: "surviving_physical" | "reconstruction" | "hypothesis" | "counterfactual_simulation" | "inscription_derived";
  notes: string;
  validatedAt: string;
}

export interface OrionAblationChallenge {
  challenged: boolean;
  assumptionsAttacked: string[];
  counterfactualVulnerability: string;
  stressResult: string;
  passed: boolean;
}

export interface OperatorPromotionGate {
  status: "pending_review" | "approved" | "rejected" | "demoted";
  promotedAt?: string;
  operatorNotes?: string;
  admittedToLedger: boolean;
}

export interface SimulationRun {
  id: string;
  name: string;
  startingState: string;
  changedVariables: string;
  assumptions: string[];
  predictedOutcomes: string[];
  divergence: string;
  confidence?: number;
  createdAt: string;
  executionStatus?: SimulationLifecycleStatus;
  computeReceipt?: ComputeReceipt;
  jemmaValidation?: JemmaProvenanceValidation;
  orionAblationChallenge?: OrionAblationChallenge;
  operatorPromotionGate?: OperatorPromotionGate;
}

export interface TwinRevision {
  id: string;
  title: string;
  description: string;
  parentId?: string;
  author: string;
  timestamp: string;
  changeSummary: string;
}

export type PathfinderStage = "QUESTION" | "EVIDENCE" | "INVESTIGATION" | "CHALLENGE" | "DECISION" | "COMMIT";

export interface PathfinderRecord {
  id: string;
  question: string;
  evidence: string[];
  investigation: string;
  challenge: string;
  decision: string;
  commitStatus: "draft" | "approved" | "committed";
  createdAt: string;
}

export interface ActiveFlow {
  stage: "COLLECTION" | "STORAGE" | "TRANSFORMATION" | "DISTRIBUTION";
  title: string;
  description: string;
  rateOrVolume: string;
  lossOrEfficiency: string;
}

// ─── CAPABILITY REGISTRY & MODEL METADATA TYPES ─────────────────────────────

export interface HardwareRequirement {
  targetDevice: "CPU" | "GPU" | "NPU" | "Cloud";
  minVramGB: number;
  recommendedCpuCores: number;
  bandwidthMbps?: number;
  offlineSupport: boolean;
}

export interface ModelCapability {
  id: string; // Model identifier, e.g. "gemini-3.5-flash", "nvidia-llama3-70b", "local-mistral-7b"
  name: string;
  provider: "Google AI Studio" | "NVIDIA NIM" | "Open-Source Runtime" | "Local Edge Runtime" | "Custom Deterministic Engine" | "FPT Neural (Revoked)";
  trustState?: RailTrustState;
  latencyMs: {
    avgMs: number;
    p95Ms: number;
    rating: "realtime" | "low" | "standard" | "batch";
  };
  hardwareRequirements: HardwareRequirement;
  trustScore: number; // 0 to 100
  supportedDomains: DigitalTwinDomain[];
  capabilities: Array<
    | "fast_reasoning"
    | "physical_simulation"
    | "evidence_synthesis"
    | "boundary_permeability"
    | "strict_json"
    | "high_precision"
    | "edge_offline"
    | "deterministic"
  >;
  costPer1kTokens?: number;
  maxContextTokens?: number;
  activeStatus: "available" | "busy" | "degraded" | "offline";
}

export interface TaskModelSelectionRequest {
  taskType: "simulation" | "evidence_verification" | "realtime_telemetry" | "boundary_check" | "interpretation";
  twinDomain: DigitalTwinDomain;
  maxAllowedLatencyMs?: number;
  minTrustScore?: number;
  maxVramGB?: number;
  requireOffline?: boolean;
  requiredCapabilities?: string[];
}

export interface EvaluatedModelMatch {
  modelId: string;
  modelName: string;
  score: number;
  eligible: boolean;
  reasons: string[];
}

export interface ModelSelectionResult {
  selectedModel: ModelCapability;
  selectionScore: number;
  matchRationales: string[];
  evaluatedModels: EvaluatedModelMatch[];
}

export interface DiscoveredConstraint {
  id: string;
  intention: string; // What MUST become true for intended outcome?
  necessaryCondition: string; // The candidate must-condition
  status: "evidenced" | "unresolved" | "challenged" | "accepted_must" | "rejected_should";
  evidenceRefs: string[];
  falsificationTest?: string; // Counterfactual test: "If we remove this condition, can the outcome still occur?"
  isMustNotShould: boolean;
  discoveredAt: string;
  previousStateName?: string;
  actionTaken?: string;
  resultingStateName?: string;
  resultingStateChange?: string;
  metricsDelta?: Record<string, string>;
}

export interface ConstraintDiscoveryCycle {
  id: string;
  twinId: string;
  targetIntention: string;
  currentCycleStage: PathfinderStage; // "QUESTION" | "EVIDENCE" | "INVESTIGATION" | "CHALLENGE" | "DECISION" | "COMMIT"
  activeConstraints: DiscoveredConstraint[];
  resolvedStateSummary?: string;
  updatedAt: string;
}

export interface DigitalTwin {
  id: string;
  name: string;
  description: string;
  domain: DigitalTwinDomain;
  purpose: string;
  boundary: TwinBoundary;
  sourceAssets: SourceAsset[];
  entities: TwinEntity[];
  relationships: TwinRelationship[];
  states: TwinState[];
  observations: Observation[];
  interpretations: Interpretation[];
  simulations: SimulationRun[];
  revisions: TwinRevision[];
  pathfinderRecords?: PathfinderRecord[];
  activeFlows?: ActiveFlow[];
  capabilityRegistry?: ModelCapability[];
  selectedModelId?: string;
  selectedModelCapability?: ModelCapability;
  constraintCycles?: ConstraintDiscoveryCycle[];
  constraints?: DiscoveredConstraint[];
  integrityStatus: "STABLE" | "UNRESOLVED_CONSTRAINTS" | "CALIBRATION_MISMATCH" | "CHALLENGED";
  createdAt: string;
  updatedAt: string;
}

export interface SharedCrossTwinConstraint {
  id: string;
  patternName: string;
  category: "Boundary Regulation" | "Feedback Dynamics" | "Provenance & Authority" | "Permeability Balance";
  description: string;
  affectedTwinIds: string[];
  affectedTwinNames: string[];
  underlyingMustCondition: string;
  sharedEvidenceSummary: string;
  falsificationProof: string;
  crossTwinRiskLevel: "CRITICAL_MUST" | "SYSTEMIC_SHOULD" | "STABLE_INVARIANT";
}

export interface FeatureNecessityChallenge {
  id: string;
  featureName: string;
  proposedIntention: string;
  counterfactualTest: string; // "If this feature is NOT built, does the system fail its core intention?"
  verdict: "GENUINE_MUST" | "DISGUISED_SHOULD" | "REJECTED_LUXURY";
  interrogationNotes: string;
  createdAt: string;
}

export interface AgentAIBOMRecord {
  agentId: string;
  agentName: string;
  role: string;
  modelAndVersion: string;
  autonomyLevel: "HUMAN_SANCTIONED" | "BOUNDED_ADVISORY" | "FULLY_AUTONOMOUS_READ";
  authorityClass: "SOVEREIGN_OPERATOR_GATE" | "GOVERNANCE_CHECK" | "EPISTEMIC_ADVISORY";
  mcpDependencies: string[];
  credentialScope: string;
  dataReach: string;
  systemPromptVersion: string;
  lastSecurityReview: string;
  bindingConstraints: string[];
  stopConditions: string[];
  securityMembraneStatus: "ACTIVE_ENFORCEMENT" | "AUDIT_ONLY" | "BYPASS_ALERT";
}

export interface SecurityMembraneInspection {
  id: string;
  timestamp: string;
  agentName: string;
  targetMCPTool: string;
  proposedPayload: Record<string, unknown>;
  operatorAuthorizationGranted: boolean;
  runtimeSecurityCheckPassed: boolean;
  inspectionVerdict: "PERMITTED" | "BLOCKED_MALFORMED_CALL" | "BLOCKED_EXCESS_PERMISSIONS" | "BLOCKED_PROMPT_INJECTION_RISK";
  securityRationale: string;
  provenanceLedgerHash: string;
}

export type EpistemicAgentName = "Alice" | "Astra" | "Jemma" | "Claudia" | "Orion" | "Natalia" | "Iris" | "Aria";

export interface EpistemicAgent {
  id: string;
  name: EpistemicAgentName;
  role: string;
  epistemicQuestion: string; // The core epistemic question this agent owns
  domainScope: string;
  isCoreSovereignLoop: boolean;
  activeStatus: "IDLE" | "ASKING" | "VALIDATING" | "CHALLENGING" | "ROUTING" | "STOP_CHECK";
  avatarColor: string;
}

export interface AgentConstraintEvaluation {
  agentName: EpistemicAgentName;
  questionAsked: string;
  agentClaim: string;
  supportingEvidenceRefs: string[];
  passedGovernanceCheck: boolean;
  operatorApprovalRequired: boolean;
  timestamp: string;
}


// Legacy compatibility aliases if required
export type DigitalTwinModel = DigitalTwin;
export type DigitalTwinComponent = TwinEntity;
export type DigitalTwinRelationship = TwinRelationship;
