// ─── DIGITAL TWIN WORKSPACE TYPES ──────────────────────────────────────────

export type DigitalTwinDomain =
  | "biological"
  | "physical"
  | "environmental"
  | "engineered"
  | "musical"
  | "conceptual"
  | "hybrid"
  | "materials"
  | "historical_kinematics"
  | "passive_cooling"
  | "culinary";

export interface BoundaryChannel {
  id: string;
  name: string;
  type: string; // e.g. "air", "water", "data", "heat", "acoustic_energy", "particle"
  rate?: string;
  medium?: string;
}

export interface BoundaryRule {
  id: string;
  inputType: string;
  condition: string;
  action: "permit" | "reject" | "attenuate" | "store" | "convert" | "redirect";
  parameters?: Record<string, number | string | boolean>;
}

export interface TwinBoundary {
  description: string;
  includedEntities: string[];
  excludedEntities: string[];
  inputs: BoundaryChannel[];
  outputs: BoundaryChannel[];
  permeabilityRules?: BoundaryRule[];
}

export interface SourceAsset {
  id: string;
  name: string;
  type: string;
  size?: string;
  url?: string;
  timestamp: string;
}

export interface TwinEntity {
  id: string;
  name: string;
  type: string;
  state: Record<string, unknown>;
  description?: string;
  status?: "active" | "warning" | "error" | "offline";
}

export interface TwinRelationship {
  id: string;
  sourceId: string;
  targetId: string;
  relationshipType: string;
  medium?: string;
  strength?: number; // 0 to 1
  latency?: number; // in ms
  direction?: "one_way" | "two_way" | "field";
}

export interface TwinState {
  id: string;
  name: string;
  metrics: Record<string, unknown>;
  timestamp: string;
  active?: boolean;
}

export type EvidenceClassification =
  | "surviving_physical"
  | "inscription_derived"
  | "reconstruction"
  | "hypothesis"
  | "counterfactual_simulation";

export interface Observation {
  id: string;
  fact: string;
  value: string;
  isFact: boolean; // true = Fact/Measured, false = Inference/Assumption
  timestamp: string;
  quality?: "measured" | "inferred" | "sensor";
  evidenceClass?: EvidenceClassification;
  sourceAssetId?: string;
}

export interface Interpretation {
  id: string;
  claim: string;
  evidenceIds: string[];
  confidence: number; // 0 to 100
  status: "observed" | "inferred" | "challenged" | "approved" | "rejected";
  createdAt: string;
  author?: string;
}

export interface SimulationPerturbation {
  targetGear?: string;
  nominalTeeth?: number;
  perturbedTeeth?: number;
  toothDelta?: number;
  moduleMm?: number;
  centerDistanceMm?: number;
  backlashMm?: number;
  pitchErrorMm?: number;
  frictionCoeff?: number;
  targetRelationship?: string;
  description?: string;
  assumptions?: string[];
  [key: string]: any;
}

export interface SimulationBaselineState {
  id?: string;
  name: string;
  description?: string;
  targetRatio?: string;
  nominalTeeth?: number;
  moduleMm?: number;
  centerDistanceMm?: number;
  status?: string;
  [key: string]: any;
}

export type ComputeRail = 
  | "NVIDIA_NIM" 
  | "RAPIDS_GPU" 
  | "OPEN_SOURCE_INFERENCE"
  | "LOCAL_DETERMINISTIC" 
  | "CUSTOM_PDE"
  | "FPT_AI_CLOUD"; // Preserved for historical provenance reading; runtime dispatch is REVOKED

export type RailTrustState = 
  | "APPROVED"
  | "EXPERIMENTAL"
  | "UNVERIFIED"
  | "SUSPENDED"
  | "REVOKED";

export type DeploymentMode = 
  | "HOSTED_EXTERNAL"
  | "SELF_HOSTED_REMOTE"
  | "LOCAL"
  | "OFFLINE_LOCAL";

export type CredentialState = 
  | "CONFIGURED"
  | "NOT_REQUIRED"
  | "MISSING"
  | "INVALID"
  | "REVOKED";

export type RailHealthState = 
  | "HEALTHY"
  | "DEGRADED"
  | "UNREACHABLE"
  | "REVOKED"
  | "UNKNOWN";

export interface InferenceRail {
  rail_id: string;
  provider: string;
  runtime: string; // e.g. "nvidia-nim", "vllm", "tgi", "local-deterministic", "cloud-gemini"
  deployment_mode: DeploymentMode;
  model_id: string;
  endpoint: string;
  capabilities: string[];
  trust_state: RailTrustState;
  credential_state: CredentialState;
  health_state: RailHealthState;
  execution_location: string;
  trustRationale?: string;
}

export type SimulationLifecycleStatus = 
  | "PROPOSED_SIMULATION"   // Proposed simulation specification awaiting dispatch (not executed)
  | "COMPUTE_GENERATED"     // Raw outputs generated by external compute rail, pending validation
  | "VALIDATED_EVIDENCE";   // Validated against empirical data / Operator promoted into accepted twin state

export interface ComputeReceipt {
  selectedRail: ComputeRail;
  endpointOrModel: string;
  inputManifest: Record<string, any>;
  codeVersion: string;
  hardwareMetadata: {
    device: string;
    accelerator?: string;
    memoryGb?: number;
    cores?: number;
    runtimeDriver?: string;
  };
  rawOutputArtifact: Record<string, any> | Array<any> | string;
  timestamp: string;
  runId: string;
  uncertaintyAndConvergence: {
    converged: boolean;
    iterations?: number;
    residualError?: number;
    confidenceBounds?: string;
    notes?: string;
  };
  inputOutputHash: string;
  fallbackOrDegradedMode: string;
}

export interface JemmaProvenanceValidation {
  validated: boolean;
  unitsChecked: boolean;
  completenessScore: number;
  evidenceClass: "surviving_physical" | "reconstruction" | "hypothesis" | "counterfactual_simulation" | "inscription_derived";
  notes: string;
  validatedAt: string;
}

export interface OrionAblationChallenge {
  challenged: boolean;
  assumptionsAttacked: string[];
  counterfactualVulnerability: string;
  stressResult: string;
  passed: boolean;
}

export interface OperatorPromotionGate {
  status: "pending_review" | "approved" | "rejected" | "demoted";
  promotedAt?: string;
  operatorNotes?: string;
  admittedToLedger: boolean;
}

export interface SimulationRun {
  id: string;
  name: string;
  startingState: string;
  changedVariables: string;
  assumptions: string[];
  predictedOutcomes: string[];
  divergence: string;
  confidence?: number;
  createdAt: string;
  executionStatus?: SimulationLifecycleStatus;
  computeReceipt?: ComputeReceipt;
  jemmaValidation?: JemmaProvenanceValidation;
  orionAblationChallenge?: OrionAblationChallenge;
  operatorPromotionGate?: OperatorPromotionGate;
}

export interface TwinRevision {
  id: string;
  title: string;
  description: string;
  parentId?: string;
  author: string;
  timestamp: string;
  changeSummary: string;
}

export type PathfinderStage = "QUESTION" | "EVIDENCE" | "INVESTIGATION" | "CHALLENGE" | "DECISION" | "COMMIT";

export interface PathfinderRecord {
  id: string;
  question: string;
  evidence: string[];
  investigation: string;
  challenge: string;
  decision: string;
  commitStatus: "draft" | "approved" | "committed";
  createdAt: string;
}

export interface ActiveFlow {
  stage: "COLLECTION" | "STORAGE" | "TRANSFORMATION" | "DISTRIBUTION";
  title: string;
  description: string;
  rateOrVolume: string;
  lossOrEfficiency: string;
}

// ─── CAPABILITY REGISTRY & MODEL METADATA TYPES ─────────────────────────────

export interface HardwareRequirement {
  targetDevice: "CPU" | "GPU" | "NPU" | "Cloud";
  minVramGB: number;
  recommendedCpuCores: number;
  bandwidthMbps?: number;
  offlineSupport: boolean;
}

export interface ModelCapability {
  id: string; // Model identifier, e.g. "gemini-3.5-flash", "nvidia-llama3-70b", "local-mistral-7b"
  name: string;
  provider: "Google AI Studio" | "NVIDIA NIM" | "Open-Source Runtime" | "Local Edge Runtime" | "Custom Deterministic Engine" | "FPT Neural (Revoked)" | "OpenAI";
  trustState?: RailTrustState;
  latencyMs: {
    avgMs: number;
    p95Ms: number;
    rating: "realtime" | "low" | "standard" | "batch";
  };
  hardwareRequirements: HardwareRequirement;
  trustScore: number; // 0 to 100
  supportedDomains: DigitalTwinDomain[];
  capabilities: Array<
    | "fast_reasoning"
    | "physical_simulation"
    | "evidence_synthesis"
    | "boundary_permeability"
    | "strict_json"
    | "high_precision"
    | "edge_offline"
    | "deterministic"
    | "advisory_reasoning"
    | "semantic_interpretation"
    | "hypothesis_generation"
  >;
  costPer1kTokens?: number;
  maxContextTokens?: number;
  activeStatus: "available" | "busy" | "degraded" | "offline";
  // Weave Router 2.0 & Empirical Routing Fields (18 Sept 2026 Brief)
  observed_task_success?: number; // Observed task success rate percentage (e.g. 96.4%)
  escalation_target?: string;     // Model/Rail ID to escalate to when task complexity/drift increases
  cache_affinity?: number;        // KV cache / prefix-cache efficiency index (0-100%)
  measured_cost_per_completed_task?: number; // Empirical $/task rather than nominal input/output token price
  routerEscalationRule?: {
    difficultyThreshold: "EASY" | "MEDIUM" | "HARD" | "CRITICAL";
    escalateOnFailure: boolean;
    fallbackRailId?: string;
  };
}

export interface TaskModelSelectionRequest {
  taskType: "simulation" | "evidence_verification" | "realtime_telemetry" | "boundary_check" | "interpretation";
  twinDomain: DigitalTwinDomain;
  maxAllowedLatencyMs?: number;
  minTrustScore?: number;
  maxVramGB?: number;
  requireOffline?: boolean;
  requiredCapabilities?: string[];
}

export interface EvaluatedModelMatch {
  modelId: string;
  modelName: string;
  score: number;
  eligible: boolean;
  reasons: string[];
}

export interface ModelSelectionResult {
  selectedModel: ModelCapability;
  selectionScore: number;
  matchRationales: string[];
  evaluatedModels: EvaluatedModelMatch[];
}

export interface DiscoveredConstraint {
  id: string;
  intention: string; // What MUST become true for intended outcome?
  necessaryCondition: string; // The candidate must-condition
  status: "evidenced" | "unresolved" | "challenged" | "accepted_must" | "rejected_should";
  evidenceRefs: string[];
  falsificationTest?: string; // Counterfactual test: "If we remove this condition, can the outcome still occur?"
  isMustNotShould: boolean;
  discoveredAt: string;
  previousStateName?: string;
  actionTaken?: string;
  resultingStateName?: string;
  resultingStateChange?: string;
  metricsDelta?: Record<string, string>;
}

export interface ConstraintDiscoveryCycle {
  id: string;
  twinId: string;
  targetIntention: string;
  currentCycleStage: PathfinderStage; // "QUESTION" | "EVIDENCE" | "INVESTIGATION" | "CHALLENGE" | "DECISION" | "COMMIT"
  activeConstraints: DiscoveredConstraint[];
  resolvedStateSummary?: string;
  updatedAt: string;
}

export interface DigitalTwin {
  id: string;
  name: string;
  description: string;
  domain: DigitalTwinDomain;
  purpose: string;
  boundary: TwinBoundary;
  sourceAssets: SourceAsset[];
  entities: TwinEntity[];
  relationships: TwinRelationship[];
  states: TwinState[];
  observations: Observation[];
  interpretations: Interpretation[];
  simulations: SimulationRun[];
  revisions: TwinRevision[];
  pathfinderRecords?: PathfinderRecord[];
  activeFlows?: ActiveFlow[];
  capabilityRegistry?: ModelCapability[];
  selectedModelId?: string;
  selectedModelCapability?: ModelCapability;
  constraintCycles?: ConstraintDiscoveryCycle[];
  constraints?: DiscoveredConstraint[];
  evidenceEnvelopes?: EvidenceEnvelope[];
  integrityStatus: "STABLE" | "UNRESOLVED_CONSTRAINTS" | "CALIBRATION_MISMATCH" | "CHALLENGED";
  createdAt: string;
  updatedAt: string;
}

export interface SharedCrossTwinConstraint {
  id: string;
  patternName: string;
  category: "Boundary Regulation" | "Feedback Dynamics" | "Provenance & Authority" | "Permeability Balance";
  description: string;
  affectedTwinIds: string[];
  affectedTwinNames: string[];
  underlyingMustCondition: string;
  sharedEvidenceSummary: string;
  falsificationProof: string;
  crossTwinRiskLevel: "CRITICAL_MUST" | "SYSTEMIC_SHOULD" | "STABLE_INVARIANT";
}

export interface FeatureNecessityChallenge {
  id: string;
  featureName: string;
  proposedIntention: string;
  counterfactualTest: string; // "If this feature is NOT built, does the system fail its core intention?"
  verdict: "GENUINE_MUST" | "DISGUISED_SHOULD" | "REJECTED_LUXURY";
  interrogationNotes: string;
  createdAt: string;
}

export interface AgentAIBOMRecord {
  agentId: string;
  agentName: string;
  role: string;
  modelAndVersion: string;
  autonomyLevel: "HUMAN_SANCTIONED" | "BOUNDED_ADVISORY" | "FULLY_AUTONOMOUS_READ";
  authorityClass: "SOVEREIGN_OPERATOR_GATE" | "GOVERNANCE_CHECK" | "EPISTEMIC_ADVISORY";
  mcpDependencies: string[];
  credentialScope: string;
  dataReach: string;
  systemPromptVersion: string;
  lastSecurityReview: string;
  bindingConstraints: string[];
  stopConditions: string[];
  securityMembraneStatus: "ACTIVE_ENFORCEMENT" | "AUDIT_ONLY" | "BYPASS_ALERT";
}

export interface SecurityMembraneInspection {
  id: string;
  timestamp: string;
  agentName: string;
  targetMCPTool: string;
  proposedPayload: Record<string, unknown>;
  operatorAuthorizationGranted: boolean;
  runtimeSecurityCheckPassed: boolean;
  inspectionVerdict: "PERMITTED" | "BLOCKED_MALFORMED_CALL" | "BLOCKED_EXCESS_PERMISSIONS" | "BLOCKED_PROMPT_INJECTION_RISK";
  securityRationale: string;
  provenanceLedgerHash: string;
}

export type EpistemicAgentName = "Alice" | "Astra" | "Jemma" | "Claudia" | "Orion" | "Natalia" | "Iris" | "Aria";

export interface EpistemicAgent {
  id: string;
  name: EpistemicAgentName;
  role: string;
  epistemicQuestion: string; // The core epistemic question this agent owns
  domainScope: string;
  isCoreSovereignLoop: boolean;
  activeStatus: "IDLE" | "ASKING" | "VALIDATING" | "CHALLENGING" | "ROUTING" | "STOP_CHECK";
  avatarColor: string;
}

export interface AgentConstraintEvaluation {
  agentName: EpistemicAgentName;
  questionAsked: string;
  agentClaim: string;
  supportingEvidenceRefs: string[];
  passedGovernanceCheck: boolean;
  operatorApprovalRequired: boolean;
  timestamp: string;
}

// ── RECOVERED COGNITIVE MACHINERY (Game_one Convergence) ─────────────────────

export type PipelineStepStatus = "COMPLETED" | "ACTIVE" | "PENDING" | "HALTED";

export interface PipelineStep {
  stepNumber: string;
  name: string;
  actor: string;
  role: string;
  actionSummary: string;
  status: PipelineStepStatus;
  details: string;
  outputs?: string[];
  refusalCriteria?: string;
  predicateCheck?: {
    predicateName: string;
    passed: boolean;
    rationale: string;
  };
  stateBadge?: string;
  badgeColor?: string;
}

export interface CausalSignalPipeline {
  id: string;
  title: string;
  category: "FRONTIER_HARDWARE" | "COMMERCIAL_DISTRIBUTION_MODEL4" | "ENERGY_PLASMA" | "PHYSICAL_TWIN_TELEMETRY";
  sourceDomain: string;
  currentStepIndex: number;
  materiality: "CRITICAL" | "HIGH" | "MEDIUM";
  signalToNoise: "SURFACE" | "FILTERED";
  epistemicState: "SOURCE VERIFIED" | "CLAIM VALIDATED" | "HYPOTHESIS VALIDATED" | "OPERATOR APPROVED";
  disagreementState?: {
    agent: string;
    challenge: string;
    status: "ACTIVE_OBJECTION" | "RESOLVED" | "UNATTESTED";
  };
  steps: PipelineStep[];
  ledgerReceiptHash?: string;
  operatorSigned?: boolean;
}

export interface ParallelBranchReceipt {
  receiptId: string;
  branchId: "BRANCH_ENERGY" | "BRANCH_DYNAMICS" | "BRANCH_COUNTERFACTUAL" | "BRANCH_SIMON_REASONING" | "BRANCH_DETERMINISTIC" | "BRANCH_PROVENANCE";
  assignedAgent: string;
  hypothesisTitle: string;
  epistemicTier: "MEASURED" | "DERIVED" | "INFERRED";
  provenanceHash: string;
  executionDurationMs: number;
  physicalPredicatesSatisfied: boolean;
  findings: string[];
  numericalMetrics: Record<string, string>;
  receiptSignature: string;
}

export interface OctagonPredicateConjunction {
  pSource: boolean;
  pProvenance: boolean;
  pPhysics: boolean;
  pSafety: boolean;
  pAuthority: boolean;
  overallPass: boolean;
  refusalCode?: string;
  refusalReason?: string;
}

export interface ParallelCognitionSession {
  sessionId: string;
  scenario: "NOMINAL" | "TWR_COLLAPSE" | "COLD_ELECTROCHEMICAL" | "INFERRED_LEAKAGE" | "STALE_FRAME";
  branches: ParallelBranchReceipt[];
  jemmaAuditPassed: boolean;
  jemmaAuditViolations: string[];
  aliceSynthesis: string;
  octagonConjunction: OctagonPredicateConjunction;
  operatorAuthorized: boolean;
  committedState: boolean;
  aetherLedgerReceipt?: string;
}

export interface BasePair {
  id: string;
  stepNumber: string;
  learningSide: {
    phase: string;
    description: string;
    learnerState: string;
  };
  teachingSide: {
    phase: string;
    description: string;
    agent: string;
    adaptation: string;
  };
  bridgeType: "ENCOUNTER" | "DIAGNOSIS" | "FEEDBACK" | "EVIDENCE" | "TRANSFER_CHALLENGE" | "FADE_SUPPORT";
  status: "COMPLETED" | "ACTIVE" | "PENDING";
}

export interface LearningBasePair {
  pairId: string;
  pairType: "ENCOUNTER" | "DIAGNOSIS" | "FEEDBACK" | "EVIDENCE" | "TRANSFER_CHALLENGE" | "FADE_SUPPORT";
  learnerState: string;
  teachingState: string;
  prompt: string;
  expectedEvidenceCriterion: string;
  scaffoldHint: string;
}

export interface HelixSimulationScenario {
  id?: string;
  scenarioId?: string;
  conceptTitle?: string;
  domain: string;
  targetCompetency?: string;
  pedagogicalObjective?: string;
  currentStageIndex?: number;
  scaffoldingLevel?: "LOW" | "MEDIUM" | "HIGH";
  learnerProfile?: string;
  learnerHistory?: any[];
  activeBasePair?: LearningBasePair;
  currentTurnIndex?: number;
  currentCycle?: number;
  masteryCriteria?: {
    recognisePattern: boolean;
    explainOwnWords: boolean;
    applyWithoutCopying: boolean;
    transferChangedContext: boolean;
    identifyBoundaryBreak: boolean;
  };
  basePairs?: BasePair[];
}

export interface CrucibleAttackTest {
  id: string;
  attackName: string;
  targetInvariant: string;
  attackVector: string;
  simulatedPayload: Record<string, unknown>;
  expectedRefusalCode: string;
  actualRefusalCode?: string;
  auditProof: string;
  executionStatus: "UNTESTED" | "REFUSED_AS_EXPECTED" | "FAILED_VULNERABILITY_LEAK";
  receiptHash?: string;
}

export interface DailyCheckpointAuditReceipt {
  timestamp: string;
  checkpoint: string;
  auditorModel: string;
  buildStatus: "SUCCESS" | "FAILED";
  executiveVerdict: "PASS" | "PASS_WITH_CONDITIONS" | "FAIL";
  verifiedClaims: string[];
  unverifiedClaims: string[];
  criticalFindings: string[];
  securityFindings: Array<{
    id: string;
    title: string;
    severity: "P1" | "P2" | "P3";
    description: string;
    correctionOrMitigation: string;
  }>;
  transactionalIntegrityAudit: {
    getBeforeWrite: boolean;
    idempotentRetries: boolean;
    runTransactionWrapped: boolean;
  };
  realtimeSubscriptionAudit: {
    subscriptionsChecked: number;
    cleanupOnUnmountVerified: boolean;
  };
  offlineReconciliationAudit: {
    cacheFallback: boolean;
    optimisticQueue: boolean;
    lastWriteWinsControlled: boolean;
  };
  adversarialCrucibleAudit: {
    attacksExecuted: number;
    attacksRefusedAsExpected: number;
    zeroVulnerabilitiesConfirmed: boolean;
  };
}

// ─── EXTENDED EVIDENCE ENVELOPE (18 September 2026 Research Brief) ────────────
// Orthogonal Axis: EPISTEMIC CLASS × EXECUTION DOMAIN × EXECUTION RECEIPT

export type EpistemicClass = 
  | "MEASURED"   // Direct physical sensor / telemetry observation
  | "DERIVED"    // Exact deterministic physics / mathematical invariant / conservation law
  | "INFERRED"   // Model inference / heuristic / LLM cognitive interpretation
  | "SIMULATED"; // Forward twin PDE / multi-physics / CFD trajectory simulation

export type ExecutionDomain =
  | "VEHICLE_EDGE" // Aircraft Jetson Orin Nano / embedded microcontroller sensor bus (<15W)
  | "LOCAL"        // Local Pathfinder Workstation (V8 / AVX-512 / UI / Graph operations)
  | "LAN_NODE"     // LAN edge node / near-field rack
  | "REMOTE_GPU"   // Remote GPU cluster (H100 / RTX 4090 / CUDA-X / cuDF)
  | "CLOUD";       // Cloud frontier model / API fabric

export interface ExecutionReceipt {
  receiptId: string;
  artifact: {
    artifactId: string;
    artifactType: string;
    rawSummary: string;
    contentHash: string;
    uriOrPayload?: any;
  };
  hardware: {
    device: string;                // e.g. "Jetson Orin Nano (15W)", "AMD Ryzen AI 9 HX 370", "NVIDIA RTX 4090", "H100 SXM5"
    architecture?: string;        // e.g. "ARMv8.2-A Cortex-A78AE + Ampere", "x86_64 Zen 5 + XDNA 2", "Ada Lovelace"
    accelerator?: string;
    memoryGb?: number;
    powerEnvelopeWatts?: number;  // Power envelope e.g. 15W, 45W, 450W
  };
  runtime: {
    engine: string;               // e.g. "TensorRT 10.3", "ROCm Hyperloom", "cuDF / CUDA-X v24.08", "Local V8 AVX-512", "Google GenAI SDK"
    version: string;
    driverVersion?: string;
  };
  inputs: {
    manifestHash: string;
    parameterCount?: number;
    samplePayloadSummary: Record<string, any>;
  };
  output: {
    primaryMetric: string;
    value: any;
    units: string;
    uncertaintyBounds?: string;
    validRange?: [number, number];
  };
  latency: {
    elapsedMs: number;
    computeMs: number;
    transferMs?: number;
  };
  power: {
    measuredJoules?: number;
    averageWatts?: number;
    batteryImpactMah?: number;
  };
  provenance: {
    timestamp: string;
    sourceNodeId: string;
    immutableSignature: string;
    operatorAttestation?: string;
    parentReceiptId?: string;
  };
  // CUDA-X / Dataframe Fallback & Execution Verification fields (Brief Item 5)
  cudaXFallbackAudit?: {
    requestedCapability: "GPU_DATAFRAME" | "GPU_TENSOR" | "GPU_CFD_SOLVER" | "GPU_INFERENCE";
    selectedBackend: string;      // e.g. "cuDF", "TensorRT", "cuML"
    actualExecution: "GPU" | "CPU_FALLBACK";
    fallbackReason?: string;      // e.g. "VRAM spillover avoided", "Operator policy restricted", "Zero GPU detected"
    bytesProcessed?: number;
    transferCostMs?: number;
    elapsedMs?: number;
  };
}

// NemoClaw Epistemic Separation Stores & Mutation Rules
export type EpistemicStoreType =
  | "AETHER_EVIDENCE"       // Immutable append-only audit trail
  | "ASTRA_STATE"          // Durable vehicle knowledge & long-term mission state (LocalLSTC)
  | "CLAUDIA_PROPOSAL"     // Ephemeral agent routing recommendations & exploratory hypotheses
  | "OCTAGON_PERMISSION"   // Sovereign permission check & safety invariant enforcement
  | "OPERATOR_ACTION";     // Sovereign human operator command & envelope definition

export type EpistemicMutationRule =
  | "APPEND_ONLY_AUDIT"
  | "DURABLE_TRANSACTION"
  | "EPHEMERAL_PROPOSAL"
  | "SOVEREIGN_GATE"
  | "MANUAL_OVERRIDE";

export interface EvidenceEnvelope<T = any> {
  id: string;
  variableName: string;
  value: T;
  units: string;
  epistemicClass: EpistemicClass;
  executionDomain: ExecutionDomain;
  executionReceipt: ExecutionReceipt;
  // NemoClaw Epistemic Separation & Mutation Guard
  epistemicStore: EpistemicStoreType;
  mutationRule: EpistemicMutationRule;
  // LocalLSTC Bound: persistent mission state owned by Astra, not reconstructed every cycle
  longTermMissionStateBound?: boolean;
}

// ─── EPISTEMIC SEPARATION QUAD & BOUNDED OPERATIONAL ENVELOPE (BOE) ──────────

export type EpistemicTier =
  | "MEASURED"     // Direct physical sensor observation
  | "ESTIMATED"    // Observer / Kalman / reconstructed state
  | "SIMULATED"    // Forward twin model / PDE prediction
  | "RECOMMENDED"; // Agent / optimizer candidate action

export interface EpistemicObject<T = any> {
  id: string;
  variableName: string;
  value: T;
  units: string;
  tier: EpistemicTier;
  provenance: {
    sourceId: string; // Sensor ID, Estimator ID, Twin run ID, or Agent ID
    timestamp: string;
    confidenceBounds?: [number, number];
    sampleFrequencyHz?: number;
  };
  immutableSignature: string;
}

export interface BoundedOperationalEnvelope {
  id: string;
  name: string;
  authorizedBy: string; // Sovereign Human Operator identity
  authorizedAt: string;
  domain: string;
  version: string;
  stateBounds: Array<{
    variable: string;
    units: string;
    min: number;
    max: number;
    criticalEmergencyThreshold: number;
    rateLimitPerSecond?: number;
  }>;
  reflexLoopFrequencyHz: number; // e.g. 50-100Hz (10-20ms)
  failClosedAction: "STOP" | "SCRAM" | "QUENCH_TO_SAFE_IDLE";
  authorityInvariant: "Authority defines the permissible state-space (Omega_safe). Machine executes deterministic reflex control inside it, but may never redefine it.";
}

export interface ReflexControlCycle {
  cycleId: string;
  timestamp: string;
  measuredState: EpistemicObject<number>;
  estimatedCoreState: EpistemicObject<number>;
  simulatedTrajectory: EpistemicObject<number>;
  agentRecommendedAction: EpistemicObject<number>;
  policyVerified: boolean;
  insideEnvelope: boolean;
  executionAction: "ACTUATE_REFLEX" | "DETERMINISTIC_STOP";
  latencyMs: number;
  ledgerCommitHash: string;
}

export interface SubstrateReviewRecord {
  id: string;
  title: string;
  sourceMatter: string;
  authorizingEntity: string;
  timestamp: string;
  disposition: "ADAPT" | "ADOPT" | "HOLD" | "REJECT";
  domainGeneralizations: {
    commonKernelVsMachineSpecific: string;
    simulationPreDeploymentReasoning: string;
    stateEstimationToFeedbackLoop: string;
    deterministicSafetySeparatedFromAI: string;
    constraintEnforcementFailClosed: string;
    provenanceRequirements: string;
    humanAuthorityBoundaries: string;
    crossTerrainModularity: string;
  };
  epistemicAudit: {
    observed: string[];
    derived: string[];
    analogy: string[];
    speculativeRejected: string[];
  };
  sovereignKernelTest: {
    formula: string;
    invariant: string;
    timescaleDecoupling: string;
  };
  minimumArchitecturalChange: string;
}

// ─── ALICE VESSEL & PATHFINDER COGNITION SHARED CONTRACT ─────────────────────

export interface PhysicalAcquisitionProof {
  hardwareSensorId: string;
  physicalCalibrationDate: string;
  rawSampleHash: string;
  telemetryIngestUri?: string;
  signalNoiseRatioDb?: number;
}

export interface VesselModelResultEnvelope<T = any> {
  envelopeId: string;
  modelIdentifier: 
    | "AliceVessel.FieldGeometry"
    | "AliceVessel.EnergyAccounting"
    | "AliceVessel.CCV01Engine"
    | "AliceVessel.VolumetricCavity"
    | "AliceVessel.TransportMedium"
    | string;
  modelVersion: string; // e.g. "a2ddbd0-v1.0"
  parameters: Record<string, any>; // interface or simulation parameters
  output: {
    variable: string;
    value: T;
    units: string;
    tensorShape?: number[];
    uncertainty?: { min: number; max: number; sigma?: number };
  };
  epistemicClass: EpistemicClass;
  physicalAcquisitionProof?: PhysicalAcquisitionProof;
  executionDomain: ExecutionDomain;
  executionReceipt: ExecutionReceipt;
  publishedAt: string;
}

export interface CognitionChallengeRecord {
  challengeId: string;
  targetEnvelopeId: string;
  cognitiveModelId: string; // e.g. "Pathfinder.Cognition-Reasoner"
  epistemicStatus: "INFERRED"; // Always strictly INFERRED, never collapsed to SIMULATED
  challengeType:
    | "HYPOTHESIS_TEST"
    | "BOUNDARY_STRESS"
    | "COUNTER_EXAMPLE"
    | "ASSUMPTION_AUDIT"
    | "ANALOGY_PROJECTION";
  interpretation: string;
  challengesRaised: string[];
  falsificationCriteria: string[];
  recommendedAction: "HOLD" | "REFINE_EXPERIMENT" | "PROPOSE_TRANSITION" | "REJECT";
  createdAt: string;
}

export interface ProposedStateTransition {
  proposalId: string;
  sourceEnvelopeId: string;
  challengeRecordId: string;
  proposedChange: {
    targetSystemComponent: string;
    currentStateVariable: string;
    currentBaselineValue: any;
    proposedBaselineValue: any;
    units: string;
    rationale: string;
  };
  octagonSafetyEvaluation: {
    evaluatedAt?: string;
    status: "PENDING" | "CONTAINED_SAFE" | "VIOLATION_BLOCKED";
    stateContainmentVerified: boolean; // x_t \in \Omega_{safe}
    invariantsChecked: string[];
    violations?: string[];
  };
  operatorPromotionGate: {
    requiredAuthority: "SOVEREIGN_HUMAN_OPERATOR";
    status: "AWAITING_OPERATOR" | "PROMOTED_TO_BASELINE" | "DECLINED";
    promotedBy?: string;
    promotedAt?: string;
    operatorNotes?: string;
    versionedCommitHash?: string;
  };
  createdAt: string;
}

export interface VersionedSystemLedgerRecord {
  ledgerIndex: number;
  timestamp: string;
  proposalId: string;
  sourceEnvelopeId: string;
  promotedBy: string;
  targetComponent: string;
  variableName: string;
  previousValue: any;
  promotedValue: any;
  units: string;
  immutableCommitHash: string;
}

// Legacy compatibility aliases if required
export type DigitalTwinModel = DigitalTwin;
export type DigitalTwinComponent = TwinEntity;
export type DigitalTwinRelationship = TwinRelationship;

